config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'skills' => 'static_pages#skills'
  get 'projects' => 'static_pages#projects'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def about
	end
	def skills
	end
	def projects
	end
	def contact
	end
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'partials/navbar' %>
    <%= yield %>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer>
	<h4 class = 'text-center'>WEB DEVELOPER / GAME DEVELOPER / STUDENT</h4>
</footer>

app/views/partials/_navbar.html.erb
<nav class = 'navbar navbar-default'>
	<div class="container-fluid">
	    <div class="navbar-header">
	      <%= link_to 'TED', root_path, :class => 'navbar-brand' %>
	    </div>
	    <ul class="nav navbar-nav navbar-right">
	      <li><%= link_to 'Home', root_path %></li>
	      <li><%= link_to 'About', about_path %></li>
	      <li><%= link_to 'Skills', skills_path %></li>
	      <li><%= link_to 'Projects', projects_path %></li>
	      <li><%= link_to 'Contact', contact_path %></li>
	    </ul>
	</div>
</nav>

app/views/static_pages/about.html.erb
<div class = 'container about'>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('man.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>Hi! I am Christian Ted Ochoa. I am an IT student of the University of San Carlos. I am from the Phiilippines.</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('gamepad.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>I love video games! They make my computers feel alive. I play them to feel happy.</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('html.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>I love to code as well! Coding makes me feel like a wizard that can take over cyberspace. I love to code to help the community.</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('happy.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>For this year, I want to be healthy and happy!</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-4 tile-icon'>
			<%= image_tag('star.png', :class => 'about-img center-block') %>
		</div>
		<div class = 'col-md-8 tile-body'>
			<p>In the near future, I want to be a game programmer. I want to make the Philippines a renowned producer of games!!!</p>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<div class = 'container contact'>
	<h1 class = 'text-center'>You can reach me through the following links</h1>
	<hr>
	<div class = 'row'>
		<div class = 'col-md-4'>
			<div class = 'contact-box'>
				<a href = 'https://www.facebook.com/christianted.ochoa.18' ><span class = 'fa fa-facebook'></span></a>
			</div>
		</div>
		<div class = 'col-md-4'>
			<div class = 'contact-box'>
				<a href = 'https://github.com/Ted125'><span class = 'fa fa-github'></span></a>
			</div>
		</div>
		<div class = 'col-md-4'>
			<div class = 'contact-box'>
				<a href = 'https://plus.google.com/u/0/103634079545684706937'><span class = 'fa fa-google-plus'></span></a>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class = 'container home text-center'>
	<h1>TED</h1>
</div>

app/views/static_pages/projects.html.erb
<div class = 'container'>
	<div class = 'row tile'>
		<div class = 'col-md-12 tile-icon'>
			<%= image_tag('my manager.png', :class => 'img img-responsive center-block') %>
		</div>
		<div class = 'col-md-12 tile-body'>
			<h2>My Manager</h2>
			<p>
				MyManager is an inventory management system software made in Java. It keeps track of a businesses’ employees, products, and orders. It can also give up-to-date statistics and print out reports.
			</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-12 tile-icon'>
			<%= image_tag('geekbook.png', :class => 'img img-responsive center-block') %>
		</div>
		<div class = 'col-md-12 tile-body'>
			<h2>Geekbook</h2>
			<p>
				Geekbook is a social networking site made in HTML, Bootstrap, and PHP. It has user, friend, posting, messaging, and CMS modules.
			</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-12 tile-icon'>
			<%= image_tag('3d_3.jpg', :class => 'img img-responsive center-block') %>
		</div>
		<div class = 'col-md-12 tile-body'>
			<h2>Toy Race Car</h2>
			<p>
				The toy race car was modeled in 3ds max, textured in photoshop, and rendered with NVidia's mental ray on 3ds max.
			</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-12 tile-icon'>
			<%= image_tag('Game_1.PNG', :class => 'img img-responsive center-block') %>
		</div>
		<div class = 'col-md-12 tile-body'>
			<h2>Infinite Runner App</h2>
			<p>
				The infinite runner app was made in Unity for Android. It was designed to run forever (obviously).
			</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-12 tile-icon'>
			<%= image_tag('Game_2.PNG', :class => 'img img-responsive center-block') %>
		</div>
		<div class = 'col-md-12 tile-body'>
			<h2>Racing Game</h2>
			<p>
				The racing game was also made in Unity but for the PC. It also features an AI enemy to challenge the player.
			</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-12 tile-icon'>
			<%= image_tag('Game_3.PNG', :class => 'img img-responsive center-block') %>
		</div>
		<div class = 'col-md-12 tile-body'>
			<h2>Maze Game</h2>
			<p>
				The 3d maze game was made in Unity for the PC. It features cel-shaded graphics and one tricky maze. You have to escape the maze together with the boulder before time expires to win.
			</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-12 tile-icon'>
			<%= image_tag('event_2.jpg', :class => 'img img-responsive center-block') %>
		</div>
		<div class = 'col-md-12 tile-body'>
			<h2>Film Fest Poster</h2>
			<p>
				This is the poster I made for our team's entry in last year's USC film festival. It was composited and retouched in Photoshop. I was very happy to know that it won people's choice for best poster!
			</p>
		</div>
	</div>
	<div class = 'row tile'>
		<div class = 'col-md-12 tile-icon'>
			<%= image_tag('event_3.jpg', :class => 'img img-responsive center-block') %>
		</div>
		<div class = 'col-md-12 tile-body'>
			<h2>Best Supporting Actor</h2>
			<p>
				Another unexpected award I got from that film festival was the best supporting actor award. I am very thankful for that.
			</p>
		</div>
	</div>
</div>

app/views/static_pages/skills.html.erb
<div class = 'container skill'>
	<div class = 'row'>
		<h2>Web Development</h2>
		<div class = 'skillbar' data-percent = '70'>
			<span class = 'skillbar-title' style = 'background-color: #E44D26;'>HTML 5</span>
			<p class = 'skillbar-bar' style = 'background-color: #F16529;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '70'>
			<span class = 'skillbar-title' style = 'background-color: #1572B6;'>CSS 3</span>
			<p class = 'skillbar-bar' style = 'background-color: #33A9DC;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '40'>
			<span class = 'skillbar-title' style = 'background-color: #131B28;'>JQuery</span>
			<p class = 'skillbar-bar' style = 'background-color: #0868AC;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '50'>
			<span class = 'skillbar-title' style = 'background-color: #292F4D;'>PHP</span>
			<p class = 'skillbar-bar' style = 'background-color: #6C7EB7;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '15'>
			<span class = 'skillbar-title' style = 'background-color: #992635;'>Rails</span>
			<p class = 'skillbar-bar' style = 'background-color: #A62E3A;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
	</div>
	<hr>
	<div class = 'row'>
		<h2>Game Development</h2>
		<div class = 'skillbar' data-percent = '90'>
			<span class = 'skillbar-title' style = 'background-color: #203239;'>Unity</span>
			<p class = 'skillbar-bar' style = 'background-color: #4E5A5F;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '55'>
			<span class = 'skillbar-title' style = 'background-color: #67217A;'>C#</span>
			<p class = 'skillbar-bar' style = 'background-color: #803788;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '90'>
			<span class = 'skillbar-title' style = 'background-color: #1D1C2E;'>Photoshop</span>
			<p class = 'skillbar-bar' style = 'background-color: #50C2FF;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '70'>
			<span class = 'skillbar-title' style = 'background-color: #006869;'>3ds Max</span>
			<p class = 'skillbar-bar' style = 'background-color: #00B1AD;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
	</div>
	<hr>
	<div class = 'row'>
		<h2>Desktop</h2>
		<div class = 'skillbar' data-percent = '60'>
			<span class = 'skillbar-title' style = 'background-color: #974700;'>Java</span>
			<p class = 'skillbar-bar' style = 'background-color: #E76F00;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
		<div class = 'skillbar' data-percent = '80'>
			<span class = 'skillbar-title' style = 'background-color: #608e1b;'>C</span>
			<p class = 'skillbar-bar' style = 'background-color: #89CD2A;'></p>
			<span class = 'skill-bar-percent'></span>
		</div>
	</div>
</div>
<script>
	$(document).ready(function(){
		$('.skillbar').skillBars({
			from: 0,
			to: false,
			speed: 1000,
			interval: 100,
			decimals: 0,
			onUpdate: null,
			onComplete: null,
			classes:{
				skillBarBar: '.skillbar-bar',
				skillBarPercent: '.skill-bar-percent',
			}
		});
	});
</script>